workflows:
  flutter-build:
    name: Flutter Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.16.6
      xcode: latest
      vars:
        BUNDLE_ID: "com.industry.app"
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build iOS
        script: flutter build ios --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphoneos/*.app

publishing:
  email:
    recipients:
      - "kartik@skycap.co.in"
    notify:
      success: true
      failure: true
    release_notes: |
      "🚀" **New Release: $CM_BUILD_ID**
      - Built from branch: $CM_BRANCH
      - Commit: $CM_COMMIT_MESSAGE
      - Build URL: $CM_BUILD_URL
